# Generated by Django 5.1.1 on 2024-09-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
        ('blog', '0005_alter_post_image'),
    ]

    operations = [
    ]
